    <div class="preloader-{__s("logged_theme_color", "light")}" system-preloader>
        <div class="loadingio loadingio-spinner-ripple-c4xwekkbyc9">
            <div class="ldio-k6xrhuhg6o">
                <div></div>
                <div></div>
            </div>
        </div>
    </div>

    <script src="{_assets("js/libs/fetch.min.js")}"></script>
    <script defer>
        window.template = "{__s("template")}";
        window.site_url = "{__s("site_url")}";
        window.tawk_id = "{__s("system_tawk_id")}";
        window.titansys_echo = "{__s("titansys_echo")}";
        window.alertsound = {if __s("logged_alertsound", 1) < 2}true{else}false{/if};
        window.message_max = {__s("system_message_max")};
        window.color_primary = "{__s("system_theme_background")}";
        window.alert_position = "{if __s("language_rtl")}topRight{else}topLeft{/if}";
        window.overlap_alert_position = "{if __s("language_rtl")}bottomRight{else}bottomLeft{/if}";
        window.consent_position = "{if __s("language_rtl")}bottom-right{else}bottom-left{/if}";
        window.theme_color = "{__s("logged_theme_color", "light")}";
        window.recaptcha_status = {if __s("system_recaptcha", 2) < 2}{if empty(__s("system_recaptcha_key")) || empty(__s("system_recaptcha_secret"))}false{else}true{/if}{else}false{/if};

        var lang_datatable_processing = "{__("datatable_processing")}",
            lang_datatable_length = "{__("datatable_length_v38")}",
            lang_datatable_info = "{__("datatable_info_v38")}",
            lang_datatable_empty = "{__("datatable_empty_v38")}",
            lang_datatable_filtered = "{__("datatable_filtered_v38")}",
            lang_datatable_loading = "{__("datatable_loading")}",
            lang_datatable_zero = "{__("datatable_zero")}",
            lang_datatable_null = "{__("datatable_null")}",
            lang_datatable_first = "{__("datatable_first")}",
            lang_datatable_prev = "{__("datatable_prev")}",
            lang_datatable_next = "{__("datatable_next")}",
            lang_datatable_last = "{__("datatable_last")}",
            lang_response_went_wrong = "{__("response_went_wrong")}",
            lang_delete_title = "{__("delete_title")}",
            lang_delete_tagline = "{__("delete_tagline")}",
            lang_validate_cannotemp = "{__("validate_cannotemp")}",
            lang_alert_attention = "{__("alert_attention")}",
            lang_date_today = "{__("date_today")}",
            lang_date_yesterday = "{__("date_yesterday")}",
            lang_date_7days = "{__("date_7days")}",
            lang_date_30days = "{__("date_30days")}",
            lang_date_month = "{__("date_month")}",
            lang_date_lmonth = "{__("date_lmonth")}",
            lang_date_custom = "{__("date_custom")}",
            lang_copy_data = "{__("copy_data")}",
            lang_unknown_action_method = "{__("unknown_action_method")}",
            lang_btn_confirm = "{__("btn_confirm")}",
            lang_btn_cancel = "{__("btn_cancel")}",
            lang_suspend_user_title = "{__("suspend_user_title")}",
            lang_suspend_user_desc = "{__("suspend_user_desc")}",
            lang_unsuspend_user_title = "{__("unsuspend_user_title")}",
            lang_unsuspend_user_desc = "{__("unsuspend_user_desc")}",
            lang_response_session_false = "{__("response_session_false")}",
            lang_require_name = "{__("require_name")}",
            lang_require_email = "{__("require_email")}",
            lang_require_password = "{__("require_password")}",
            lang_require_cpassword = "{__("require_cpassword")}",
            lang_validate_cannotemp = "{__("validate_cannotemp")}",
            lang_alert_attention = "{__("alert_attention")}",
            lang_cookieconsent_message = "{__("cookieconsent_message")}",
            lang_cookieconsent_link = "{__("cookieconsent_link")}",
            lang_cookieconsent_dismiss = "{__("cookieconsent_dismiss")}",
            lang_pendingdelete_title = "{__("pendingdelete_title")}",
            lang_pendingdelete_desc = "{__("pendingdelete_desc")}",
            lang_js_loader_pleasewait = "{__("js_loader_pleasewait")}",
            lang_js_userstatus_online = "{__("js_userstatus_online")}",
            lang_js_userstatus_offline = "{__("js_userstatus_offline")}",
            lang_js_whatsapp_linksuccess = "{__("js_whatsapp_linksuccess")}",
            lang_js_whatsapp_linkfailed = "{__("js_whatsapp_linkfailed")}",
            lang_js_whatsapp_linkexist = "{__("js_whatsapp_linkexist")}",
            lang_js_whatsapp_loaderprocessing = "{__("js_whatsapp_loaderprocessing")}",
            lang_js_clearpending_title = "{__("js_clearpending_title")}",
            lang_js_clearpending_desc = "{__("js_clearpending_desc")}",
            lang_js_clearpending_processing = "{__("js_clearpending_processing")}",
            lang_js_authenticate_processing = "{__("js_authenticate_processing")}",
            lang_js_actiontrigger_title = "{__("js_actiontrigger_title")}",
            lang_js_actiontrigger_typetitle = "{__("js_actiontrigger_typetitle")}",
            lang_js_actiontrigger_typesms = "{__("js_actiontrigger_typesms")}",
            lang_js_actiontrigger_typewa = "{__("js_actiontrigger_typewa")}",
            lang_js_actiontrigger_typeussd = "{__("js_actiontrigger_typeussd")}",
            lang_js_actiontrigger_typenoti = "{__("js_actiontrigger_typenoti")}",
            lang_js_actiontrigger_loader = "{__("js_actiontrigger_loader")}",
            lang_js_actiontranslator_title = "{__("js_actiontranslator_title")}",
            lang_js_actiontranslator_from = "{__("js_actiontranslator_from")}",
            lang_js_actiontranslator_to = "{__("js_actiontranslator_to")}",
            lang_js_actiontranslator_loader = "{__("js_actiontranslator_loader")}",
            lang_js_actionregen_title = "{__("js_actionregen_title")}",
            lang_js_actionregen_desc = "{__("js_actionregen_desc")}",
            lang_js_actionregen_loader = "{__("js_actionregen_loader")}",
            lang_js_actionclear_title = "{__("js_actionclear_title")}",
            lang_js_actionclear_desc = "{__("js_actionclear_desc")}",
            lang_js_processing_dataloader = "{__("js_processing_dataloader")}",
            lang_js_build_title = "{__("js_build_title")}",
            lang_js_build_desc = "{__("js_build_desc")}",
            lang_js_build_btnbuild = "{__("js_build_btnbuild")}",
            lang_js_reorder_title = "{__("js_reorder_title")}",
            lang_js_reorder_desc = "{__("js_reorder_desc")}",
            lang_js_deletetrash_title = "{__("js_deletetrash_title")}",
            lang_js_deletetrash_desc = "{__("js_deletetrash_desc")}",
            lang_js_tablesexport_copy = "{__("js_tablesexport_copy")}",
            lang_js_tablesexport_excel = "{__("js_tablesexport_excel")}",
            lang_js_tablesexport_pdf = "{__("js_tablesexport_pdf")}",
            lang_requests_build_submitrequest = "{__("requests_build_submitrequest")}",
            lang_requests_reorder_loader = "{__("requests_reorder_loader")}",
            lang_requests_deleteitem_loader = "{__("requests_deleteitem_loader")}",
            lang_js_calendarall_option = "{__("js_calendarall_option")}",
            lang_js_calendarall_apply = "{__("js_calendarall_apply")}",
            lang_js_calendarall_cancel = "{__("js_calendarall_cancel")}",
            lang_js_calendarall_from = "{__("js_calendarall_from")}",
            lang_js_calendarall_to = "{__("js_calendarall_to")}",
            lang_js_calendarall_week = "{__("js_calendarall_week")}",
            lang_js_calendarall_daysu = "{__("js_calendarall_daysu")}",
            lang_js_calendarall_daymo = "{__("js_calendarall_daymo")}",
            lang_js_calendarall_daytu = "{__("js_calendarall_daytu")}",
            lang_js_calendarall_daywe = "{__("js_calendarall_daywe")}",
            lang_js_calendarall_dayth = "{__("js_calendarall_dayth")}",
            lang_js_calendarall_dayfr = "{__("js_calendarall_dayfr")}",
            lang_js_calendarall_daysa = "{__("js_calendarall_daysa")}",
            lang_js_calendarall_monjan = "{__("js_calendarall_monjan")}",
            lang_js_calendarall_monfeb = "{__("js_calendarall_monfeb")}",
            lang_js_calendarall_monmar = "{__("js_calendarall_monmar")}",
            lang_js_calendarall_monapr = "{__("js_calendarall_monapr")}",
            lang_js_calendarall_monmay = "{__("js_calendarall_monmay")}",
            lang_js_calendarall_monjun = "{__("js_calendarall_monjun")}",
            lang_js_calendarall_monjul = "{__("js_calendarall_monjul")}",
            lang_js_calendarall_monaug = "{__("js_calendarall_monaug")}",
            lang_js_calendarall_monsep = "{__("js_calendarall_monsep")}",
            lang_js_calendarall_monoct = "{__("js_calendarall_monoct")}",
            lang_js_calendarall_monnov = "{__("js_calendarall_monnov")}",
            lang_js_calendarall_mondec = "{__("js_calendarall_mondec")}",
            lang_response_whatsapp_creatingqr = "{__("response_whatsapp_creatingqr")}",
            lang_datatable_addedtoclipboard = "{__("datatable_addedtoclipboard")}",
            lang_datatable_addedtoclipboardkeys = "{__("datatable_addedtoclipboardkeys")}",
            lang_datatable_addedtoclipboardmulti = "{__("datatable_addedtoclipboardmulti")}",
            lang_datatable_addedtoclipboardsingle = "{__("datatable_addedtoclipboardsingle")}",
            lang_js_response_titanechorefreshdesc = "{__("js_response_titanechorefreshdesc")}",
            lang_campaign_popup_titleresume = "{__("campaign_popup_titleresume")}",
            lang_campaign_popup_titlestop = "{__("campaign_popup_titlestop")}",
            lang_campaign_popup_descsmsresume = "{__("campaign_popup_descsmsresume")}",
            lang_campaign_popup_descsmsstop = "{__("campaign_popup_descsmsstop")}",
            lang_campaign_popup_descwaresume = "{__("campaign_popup_descwaresume")}",
            lang_campaign_popup_descwastop = "{__("campaign_popup_descwastop")}",
            lang_plugin_mpg_popuppayumoneymobilenumber = "{__("plugin_mpg_popuppayumoneymobilenumber")}",
            lang_js_wa_form_audiotype_entermsg = "{__("js_wa_form_audiotype_entermsg")}",
            lang_js_wa_form_audionotavail_disinput = "{__("js_wa_form_audionotavail_disinput")}",
            lang_apexcharts_locale_monthjanuary = "{__("apexcharts_locale_monthjanuary")}",
            lang_apexcharts_locale_monthfebruary = "{__("apexcharts_locale_monthfebruary")}",
            lang_apexcharts_locale_monthmarch = "{__("apexcharts_locale_monthmarch")}",
            lang_apexcharts_locale_monthapril = "{__("apexcharts_locale_monthapril")}",
            lang_apexcharts_locale_monthmay = "{__("apexcharts_locale_monthmay")}",
            lang_apexcharts_locale_monthjune = "{__("apexcharts_locale_monthjune")}",
            lang_apexcharts_locale_monthjuly = "{__("apexcharts_locale_monthjuly")}",
            lang_apexcharts_locale_monthaugust = "{__("apexcharts_locale_monthaugust")}",
            lang_apexcharts_locale_monthseptember = "{__("apexcharts_locale_monthseptember")}",
            lang_apexcharts_locale_monthoctober = "{__("apexcharts_locale_monthoctober")}",
            lang_apexcharts_locale_monthnovember = "{__("apexcharts_locale_monthnovember")}",
            lang_apexcharts_locale_monthdecember = "{__("apexcharts_locale_monthdecember")}",
            lang_apexcharts_locale_monthjanshort = "{__("apexcharts_locale_monthjanshort")}",
            lang_apexcharts_locale_monthfebshort = "{__("apexcharts_locale_monthfebshort")}",
            lang_apexcharts_locale_monthmarshort = "{__("apexcharts_locale_monthmarshort")}",
            lang_apexcharts_locale_monthaprshort = "{__("apexcharts_locale_monthaprshort")}",
            lang_apexcharts_locale_monthmayshort = "{__("apexcharts_locale_monthmayshort")}",
            lang_apexcharts_locale_monthjunshort = "{__("apexcharts_locale_monthjunshort")}",
            lang_apexcharts_locale_monthjulshort = "{__("apexcharts_locale_monthjulshort")}",
            lang_apexcharts_locale_monthaugshort = "{__("apexcharts_locale_monthaugshort")}",
            lang_apexcharts_locale_monthsepshort = "{__("apexcharts_locale_monthsepshort")}",
            lang_apexcharts_locale_monthoctshort = "{__("apexcharts_locale_monthoctshort")}",
            lang_apexcharts_locale_monthnovshort = "{__("apexcharts_locale_monthnovshort")}",
            lang_apexcharts_locale_monthdecshort = "{__("apexcharts_locale_monthdecshort")}",
            lang_apexcharts_locale_daymonday = "{__("apexcharts_locale_daymonday")}",
            lang_apexcharts_locale_daytuesday = "{__("apexcharts_locale_daytuesday")}",
            lang_apexcharts_locale_daywednesday = "{__("apexcharts_locale_daywednesday")}",
            lang_apexcharts_locale_daythursday = "{__("apexcharts_locale_daythursday")}",
            lang_apexcharts_locale_dayfriday = "{__("apexcharts_locale_dayfriday")}",
            lang_apexcharts_locale_daysaturday = "{__("apexcharts_locale_daysaturday")}",
            lang_apexcharts_locale_daysunday = "{__("apexcharts_locale_daysunday")}",
            lang_apexcharts_locale_daymondayshort = "{__("apexcharts_locale_daymondayshort")}",
            lang_apexcharts_locale_daytuesdayshort = "{__("apexcharts_locale_daytuesdayshort")}",
            lang_apexcharts_locale_daywednesdayshort = "{__("apexcharts_locale_daywednesdayshort")}",
            lang_apexcharts_locale_daythursdayshort = "{__("apexcharts_locale_daythursdayshort")}",
            lang_apexcharts_locale_dayfridayshort = "{__("apexcharts_locale_dayfridayshort")}",
            lang_apexcharts_locale_daysaturdayshort = "{__("apexcharts_locale_daysaturdayshort")}",
            lang_apexcharts_locale_daysundayshort = "{__("apexcharts_locale_daysundayshort")}",
            lang_apexcharts_locale_exportsvg = "{__("apexcharts_locale_exportsvg")}",
            lang_apexcharts_locale_exportpng = "{__("apexcharts_locale_exportpng")}",
            lang_apexcharts_locale_menu = "{__("apexcharts_locale_menu")}",
            lang_apexcharts_locale_selection = "{__("apexcharts_locale_selection")}",
            lang_apexcharts_locale_selectionzoom = "{__("apexcharts_locale_selectionzoom")}",
            lang_apexcharts_locale_zin = "{__("apexcharts_locale_zin")}",
            lang_apexcharts_locale_zout = "{__("apexcharts_locale_zout")}",
            lang_apexcharts_locale_pan = "{__("apexcharts_locale_pan")}",
            lang_apexcharts_locale_reset = "{__("apexcharts_locale_reset")}",
            lang_waexport_loader_exporting = "{__("waexport_loader_exporting")}",
            lang_actions_waexportgroupcontacts_title = "{__("actions_waexportgroupcontacts_title")}",
            lang_actions_waexportgroupcontacts_desc = "{__("actions_waexportgroupcontacts_desc")}"
            lang_impersonate_userentry_title = "{__("impersonate_userentry_title")}",
            lang_impersonate_userentry_desc = "{__("impersonate_userentry_desc")}",
            lang_impersonate_userentry_loader = "{__("impersonate_userentry_loader")}",
            lang_impersonate_userexit_loader = "{__("impersonate_userexit_loader")}",
            lang_plugins_btn_pluginsdefopagegeneric = "{__("plugins_btn_pluginsdefopagegeneric")}",
            lang_js_regenerate_admintoken = "{__("js_regenerate_admintoken")}",
            lang_js_regenerate_admintoken_desc = "{__("js_regenerate_admintoken_desc")}";

        fetchInject([
            "{_assets("js/template.dashboard.js")}", {__s("plugin_scripts")}
        ], fetchInject([
            "{_assets("js/custom.run.js", true)}", {__s("plugin_styles")}
        ], fetchInject([
            "{_assets("js/system.js")}",
            "{_assets("js/libs/he.min.js")}",
            "{_assets("js/libs/mfb.min.js")}",
            "{_assets("js/libs/card.min.js")}",
            "{_assets("js/libs/daterangepicker.min.js")}"
        ], fetchInject([
            "{_assets("js/libs/pjax.min.js")}",
            "{_assets("js/libs/moment.min.js")}",
            "{_assets("js/libs/waves.min.js")}",
            "{_assets("js/libs/nprogress.min.js")}",
            "{_assets("js/libs/jquery.loading.min.js")}",
            "{_assets("js/libs/qrcode.min.js")}",
            "{_assets("js/libs/scrollto.min.js")}",
            "{_assets("js/libs/izitoast.min.js")}",
            "{_assets("js/libs/codeflask.min.js")}",
            "{_assets("js/libs/clipboard.min.js")}",
            "{_assets("js/libs/autocomplete.min.js")}",
            "{_assets("js/libs/iframeResizer.min.js")}",
            "{_assets("js/libs/bootstrap-select.min.js")}",
            "{_assets("js/libs/bootstrap-toggle.min.js")}",
            "{_assets("js/libs/jquery.word-and-character-counter.min.js")}",
            "{_assets("js/libs/cookieconsent.min.js")}",
            "{_assets("js/libs/datatables.min.js")}",
            "{_assets("js/libs/tooltipster.bundle.min.js")}",
            "{_assets("js/libs/alertsound.min.js")}",
            "{_assets("js/libs/jsoneditor.min.js")}",
            "{_assets("js/libs/echo.min.js")}"
        ], fetchInject([
            "{assets("js/libs/bootstrap.min.js")}"
        ], fetchInject([
            "{_assets("js/libs/jquery.min.js")}",
            "{_assets("css/custom.css", true)}",
            "{if __s("language_rtl")}{_assets("css/libs/mfb.rtl.min.css")}{else}{_assets("css/libs/mfb.min.css")}{/if}",
            "{_assets("css/libs/waves.min.css")}",
            "{_assets("css/libs/animate.min.css")}",
            "{_assets("css/libs/izitoast.min.css")}",
            "{_assets("css/libs/datatables.min.css")}",
            "{if __s("logged_theme_color", "light") eq "dark"}{_assets("css/libs/daterangepicker.dark.min.css")}{else}{_assets("css/libs/daterangepicker.min.css")}{/if}",
            "{_assets("css/libs/bootstrap-select.min.css")}",
            "{_assets("css/libs/bootstrap-toggle.min.css")}",
            "{_assets("css/libs/cookieconsent.min.css")}",
            "{_assets("css/libs/tooltipster.bundle.min.css")}",
            "{_assets("css/libs/jsoneditor.min.css")}"
        ]))))));
    </script>
</body>

</html>